guestbook/urls.py
"""guestbook URL Configuration

`urlpatterns`列表將URL路由到視圖。 有關更多信息，請參閱：
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
例如：
Function views
    1. 導入:  from my_app import views
    2. 新增URL到urlpatterns:  path('', views.home, name='home')
Class-based views
    1. 導入:  from other_app.views import Home
    2. 新增URL到urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. 導入 include() function: from django.urls import include, path
    2. 新增URL到urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django .contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/message/')),
    path('message/', include('web.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),  
]

web/urls.py
from django.urls import path
from . import views
from .views import register


urlpatterns = [
    path('', views.MessageList.as_view()),
    path('create/', views.MessageCreate.as_view()),  
    path('<int:pk>', views.MessageDetail.as_view()),
    path('<int:pk>/delete/', views.MessageDelete.as_view()),   
    path('accounts/register/', register),
]

web/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Message(models.Model):
    user = models.CharField("姓名", max_length=50)
    subject = models.CharField("主旨", max_length=200)
    post_choice = (('new', '公告'),('share', '分享'), ('info', '資訊'), ('practice', '梗圖'), ('problem', '問題'), ('other', '其他'))
    post_typel = models.CharField(max_length=30, choices=post_choice, default='new')
    content = RichTextField("內容")
    publication_date = models.DateTimeField("留言日期", auto_now_add=True)

    def __str__(self):
        return self.subject

web/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from .models import Message
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render



def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/accounts/login/')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', locals())

# 留言列表
class MessageList(ListView):
    model = Message
    ordering = ['-id']      # 以 id 欄位值由大至小反向排序

# 留言檢視
class MessageDetail(DetailView):
    model = Message

# 新增留言
class MessageCreate(CreateView):
    model = Message
    fields = ['user', 'post_typel', 'subject', 'content']     # 僅顯示 user, post_typel, subject, content 這 4 個欄位
    success_url = '/message/'                   # 新增成功後，導向留言列表
    template_name = 'form.html'                 # 指定欲使用的頁面範本

    # 刪除留言
class MessageDelete(DeleteView):
    model = Message
    success_url = '/message/'                # 刪除成功返回留言列表
    template_name = 'confirm_delete.html'
"""
    # 修改留言
class MessageUpdate(UpdateView):
    model = Message
    success_url = '/message/'                # 刪除成功返回留言列表
    template_name = 'confirm_update.html'
"""

web/templates/base1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <title>公告</title>
  </head>
  <body>
    <div class="container">
      {% include "navbar.html" %}
      {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

web/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% if perms.guestbook.remove_article %}
<h1>您確定要刪除這筆記錄嗎?</h1>
<hr>
<h2>【{{ message.get_post_typel_display }}】{{ message.subject }}</h2>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="刪除" class="btn btn-sm btn-danger" />
</form>
{% else %}
<p>你沒有權限刪除這筆記錄 !</p>
{% endif %}
{% endblock %}

web/templates/confirm_update.html
{% extends "base.html" %}

{% block content %}
<h1>刪除記錄</h1>
{% if perms.guestbook.remove_article %}
<p>您確定要刪除這筆記錄嗎?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="是的，我要刪除" class="btn btn-sm btn-danger" />
</form>
{% else %}
<p>你沒有權限刪除這筆記錄 !</p>
{% endif %}
{% endblock %}

web/templates/form.html
{% extends "base.html" %}

{% block content %}
<script src="https://cdn.ckeditor.com/4.13.1/full-all/ckeditor.js"></script>
<form name="sub" action="" method="post">
  {% csrf_token %}
  <table class="table">
    <tr style="display: none;">
      <td><input id="id_user" name="user" class="form-control" value="{{ user.username }}"></td>
    </tr>
    <tr>
      <input id="id_subject" name="subject" class="form-control" placeholder="主旨">
    </tr>
    <tr>
      <select id="id_post_type" name="post_typel" class="form-control" value="new">
        　<option value="new">公告</option>
        　<option value="share">分享</option>
        　<option value="info">資訊</option>
        　<option value="practice">梗圖</option>
        <option value="problem">問題</option>
        <option value="other">其他</option>
      </select>
    </tr>
    <tr>
      <textarea name="content" id="id_content" cols="30" rows="10" class="form-control" data-sample-preservewhitespace
        data-sample-short></textarea>
    </tr>
  </table>
  <input type="button" id="check" onclick="test()" value="送出" class="btn btn-sm btn-primary" />
  <input type="submit" id="submit" style="display: none;" class="btn btn-sm btn-primary" />
</form>
<script>
  var config = {
    removeButtons: "Scayt,PasteText,PasteFromWord,Outdent,Indent,CreateDiv,Save,Iframe,PageBreak,NewPage,Preview,Print,Templates,Find,SelectAll,Flash,About,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField",
    extraAllowedContent: "img[src,alt,width,height]",
    extraPlugins: "codesnippet,embed,autoembed,image2",
    codeSnippet_theme: "monokai_sublime",
    height: 356,
    tabSpaces: "4",
    contentsCss: [
      'http://cdn.ckeditor.com/4.13.1/full-all/contents.css',
      'https://ckeditor.com/docs/vendors/4.13.1/ckeditor/assets/css/widgetstyles.css'
    ],
    // Setup content provider. See https://ckeditor.com/docs/ckeditor4/latest/features/media_embed
    embed_provider: '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}',

    // Configure the Enhanced Image plugin to use classes instead of styles and to disable the
    // resizer (because image size is controlled by widget styles or the image takes maximum
    // 100% of the editor width).
    image2_alignClasses: ['image-align-left', 'image-align-center', 'image-align-right'],
    image2_disableResizer: true,
  };
  CKEDITOR.replace("content", config);
</script>
<script>
  Swal.fire({
    title: '插入程式碼片段',
    text: '點擊此按鈕並選取你要插入的程式語言!',
    imageUrl: 'https://s2.ax1x.com/2020/02/10/1IZpxx.png',
    imageWidth: 619,
    imageHeight: 282,
    imageAlt: '插入程式碼',
  })
  function test() {
    var user = document.getElementById('id_user').value;
    var subject = document.getElementById('id_subject').value;
    var post_type = document.getElementById('id_post_type').value;
    var $CKcontent = CKEDITOR.instances.id_content.getData();
    if (subject == "" || $CKcontent == "" || post_type == "" || user == "") {
      Swal.fire({
        type: 'error',
        title: '有空格尚未填寫',
        text: '請確實填寫主旨和內容',
      })
    }else if(user != "{{ user.username }}"){
      document.getElementById('id_user').value = "{{ user.username }}"
      document.getElementById('submit').click();
    } else {
      document.getElementById('submit').click();
    }
  }
</script>
{% endblock %}

web/templates/register.html
{% extends "base.html" %}

{% block content %}
        <h1>註冊新帳號</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="註冊">
        </form>
{% endblock %}

web/templates/web/message_detail.html
{% extends "base.html" %}

{% block content %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/a11y-dark.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
<div class="card mt-2">
  <div class="card-header d-flex justify-content-between">
    <div class="font-weight-bold"><h2>【{{ message.get_post_typel_display }}】</h2><h2> {{ message.subject }}</h2></div>
    <div class="font-weight-bold"><button class="btn btn-primary d-none d-md-block" onclick="history.back(),detect()">返回</button></div>
  </div>
  <div class="card-body">    
    <div class="card-text">{{ message.content|safe }}</div>    
  </div>
  <div class="card-footer d-flex justify-content-between">
    <small class="text-muted"><i class="fas fa-user"></i> {{ message.user }}</small>
    <small class="text-muted"><i class="fas fa-clock"></i> {{ message.publication_date|date:"Y/m/d H:i" }}</small>
  </div>
</div>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

web/templates/web/message_list.html
{% extends "base.html" %}

{% block content %}
<ul class="list-group mt-2" id="msg">
  {% for message in message_list %}
  <li class="list-group-item list-group-item-action" name="{{ message.post_typel }}">
    <small class="text-muted d-none d-lg-inline"><i class="fas fa-clock"></i> {{message.publication_date|date:"Y/m/d H:i"}}</small>
    {% if perms.guestbook.remove_article %}
    <a href="{{message.id}}/delete#new" class="text-danger" title="刪除"><i class="fas fa-minus-circle"></i></a>
    {% endif %}
    <a href="{{message.id}}#new">【{{ message.get_post_typel_display }}】{{ message.subject }}</a>
    <small class="text-muted float-right d-none d-lg-inline"><i class="fas fa-user"></i> {{ message.user }}</small>
  </li>
  {% endfor %}
</ul>
{% endblock %}